version: '3.8'

services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8
    environment:
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: sakaipass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3006:3306"

  sakai:
    build: .
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql:3306
      DATABASE_NAME: sakai
      DATABASE_USER: sakai
      DATABASE_PASSWORD: sakaipass
    ports:
      - "8080:8080"
